### ISSUE TITLE
Compilation errors are not handled

### ISSUE THREAD

**Issue by ktsn** [ko-yelie/gulp-rollup-each#2]
Hi, I noticed gulp-rollup-each outputs unhandled promise rejections like the following log if the compiled code has some syntax errors.

```bash
(node:3864) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Unexpected token
```

 I guess it is caused because gulp-rollup-each currently does not handle the errors from `rollup`.
Can we solve this problem so that providing readable errors?

**Comment by ko-yelie** [comment]
Yes, you can.

**Comment by aubergene** [comment]
I am still getting this error with version 1.0.2. I'm using rollup-plugin-svelte, and gulp breaks when it reports an error

**Comment by ko-yelie** [comment]
@aubergene Could you provide reproduction for that?
